package com.genesys.core.domain.usecase.notebook

import javax.inject.Inject

data class NotebookUseCases @Inject constructor(
    val addNotebookPageUseCase: AddNotebookPageUseCase,
    val changeNotebookPageIndexUseCase: ChangeNotebookPageIndexUseCase,
    val createNotebookEmptyUseCase: CreateNotebookEmptyUseCase,
    val createNotebookFolderUseCase: CreateNotebookFolderUseCase,
    val createNotebookImageUseCase: CreateNotebookImageUseCase,
    val createNotebookPageUseCase: CreateNotebookPageUseCase,
    val createNotebookStrokeUseCase: CreateNotebookStrokeUseCase,
    val createNotebookUseCase: CreateNotebookUseCase,
    val deleteNotebookFolderUseCase: DeleteNotebookFolderUseCase,
    val deleteNotebookImageAllUseCase: DeleteNotebookImageAllUseCase,
    val deleteNotebookKeyValueUseCase: DeleteNotebookKeyValueUseCase,
    val deleteNotebookPageUseCase: DeleteNotebookPageUseCase,
    val deleteNotebookStrokeAllUseCase: DeleteNotebookStrokeAllUseCase,
    val deleteNotebookUseCase: DeleteNotebookUseCase,
    val getNotebookByIdUseCase: GetNotebookByIdUseCase,
    val getNotebookFolderParentUseCase: GetNotebookFolderParentUseCase,
    val getNotebookFolderUseCase: GetNotebookFolderUseCase,
    val getNotebookImageByIdUseCase: GetNotebookImageByIdUseCase,
    val getNotebookKeyValueUseCase: GetNotebookKeyValueUseCase,
    val getNotebookPageAtIndexUseCase: GetNotebookPageAtIndexUseCase,
    val getNotebookPageByIdUseCase: GetNotebookPageByIdUseCase,
    val getNotebookPageByIdsUseCase: GetNotebookPageByIdsUseCase,
    val getNotebookPageImagesUseCase: GetNotebookPageImagesUseCase,
    val getNotebookPageIndexUseCase: GetNotebookPageIndexUseCase,
    val getNotebookPagePageUseCase: GetNotebookPagePageUseCase,
    val getNotebookPageStrokesUseCase: GetNotebookPageStrokesUseCase,
    val getNotebookPageWithImagesByIdUseCase: GetNotebookPageWithImagesByIdUseCase,
    val getNotebookPageWithStrokesByIdUseCase: GetNotebookPageWithStrokesByIdUseCase,
    val getNotebookStrokeByIdUseCase: GetNotebookStrokeByIdUseCase,
    val observeNotebookByIdUseCase: ObserveNotebookByIdUseCase,
    val observeNotebookFolderChildrenUseCase: ObserveNotebookFolderChildrenUseCase,
    val observeNotebookFolderFolderUseCase: ObserveNotebookFolderFolderUseCase,
    val observeNotebookInFolderUseCase: ObserveNotebookInFolderUseCase,
    val observeNotebookKeyValueUseCase: ObserveNotebookKeyValueUseCase,
    val observeNotebookPageStandalonePagesUseCase: ObserveNotebookPageStandalonePagesUseCase,
    val removeNotebookPageUseCase: RemoveNotebookPageUseCase,
    val setNotebookKeyValueUseCase: SetNotebookKeyValueUseCase,
    val setNotebookOpenPageIdUseCase: SetNotebookOpenPageIdUseCase,
    val updateNotebookFolderUseCase: UpdateNotebookFolderUseCase,
    val updateNotebookImageUseCase: UpdateNotebookImageUseCase,
    val updateNotebookPageScrollUseCase: UpdateNotebookPageScrollUseCase,
    val updateNotebookPageUseCase: UpdateNotebookPageUseCase,
    val updateNotebookStrokeUseCase: UpdateNotebookStrokeUseCase,
    val updateNotebookUseCase: UpdateNotebookUseCase
)