package com.genesys.feature.notebook.editor.utils

import android.graphics.Rect
import android.os.Build
import android.util.Log
import android.view.View
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.composed
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.input.nestedscroll.NestedScrollConnection
import androidx.compose.ui.input.nestedscroll.NestedScrollSource
import androidx.compose.ui.input.nestedscroll.nestedScroll
import androidx.compose.ui.unit.Velocity
import com.genesys.feature.notebook.editor.settings.NotebookEditorSettings
import com.genesys.feature.notebook.editor.settings.NotebookSettingsProvider
import com.genesys.feature.notebook.utils.logCallStack
import com.onyx.android.sdk.api.device.epd.EpdController
import com.onyx.android.sdk.api.device.epd.EpdController.SCHEME_NORMAL
import com.onyx.android.sdk.api.device.epd.EpdController.SCHEME_SCRIBBLE
import com.onyx.android.sdk.api.device.epd.UpdateMode
import com.onyx.android.sdk.api.device.epd.UpdateOption
import com.onyx.android.sdk.pen.TouchHelper
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

private const val TAG = "einkHelper"

/**
 * ONYX EPD REFRESH MODES GUIDE (Generated by AI, better then nothing)
 * ============================================
 *
 * ### 1. Update Modes (Quality ↔ Speed Tradeoff)
 * These control the balance between refresh speed and display quality:
 *
 * | Mode         | Description                                       |
 * |--------------|---------------------------------------------------|
 * | `GC`         | Full refresh (Best quality, slowest, no ghosting) |
 * | `GU`         | Grayscale update (Partial refresh, preserves tone)|
 * | `DU`         | Direct update (Faster, partial, moderate quality) |
 * | `ANIMATION`  | Smooth animation updates (some ghosting possible) |
 * | `A2`         | Fastest update (Lowest quality, minimal latency)  |
 * | `DEEP_GC`    | Deep clean refresh (Best for text rendering)      |
 *
 * ### 2. Display Schemes (System-Wide Presets)
 * Affect the global system behavior:
 *
 * | Scheme                        | Description                          |
 * |-------------------------------|--------------------------------------|
 * | `SCHEME_NORMAL`              | Default balanced e-ink mode          |
 * | `SCHEME_KEYBOARD`           | Optimized for keyboard input         |
 * | `SCHEME_SCRIBBLE`           | Best for handwriting/stylus input    |
 * | `SCHEME_APPLICATION_ANIMATION` | App-specific animation optimization |
 * | `SCHEME_SYSTEM_ANIMATION`   | System-wide animation optimization   |
 *
 * ### 3. Special Functions (System-Level Tools)
 *
 * | Function                  | Description                                      |
 * |---------------------------|--------------------------------------------------|
 * | `applyGCOnce()`           | Force one full-screen GC refresh                |
 * | `repaintEveryThing()`     | Repaints the entire screen with current mode    |
 * | `fillWhiteOnWakeup()`     | Clears residual ghosting on wake                |
 * | `useGCForNewSurface()`    | Forces GC when new surfaces appear              |
 * | `setEpdTurbo(int)`        | Adjusts refresh speed (0 = slow, 100 = fastest) |
 *
 * ### 4. View-Specific Controls
 * Fine-grained control per view:
 *
 * | Function                        | Description                                |
 * |----------------------------------|--------------------------------------------|
 * | `setViewDefaultUpdateMode()`    | Sets default update mode for a specific view |
 * | `resetViewUpdateMode()`         | Resets view update mode to system default   |
 * | `disableA2ForSpecificView()`    | Disables A2 mode for that view              |
 * | `handwritingRepaint()`          | Optimized refresh for handwriting regions   |
 *
 * ### 5. Waveform Controls (Advanced Tuning)
 *
 * | Function          | Description                            |
 * |-------------------|----------------------------------------|
 * | `enableRegal()`   | Enables Regal waveform for less ghosting |
 * | `disableRegal()`  | Disables Regal waveform                 |
 * | `setTrigger()`    | Sets waveform trigger count             |
 * | `byPass()`        | Skips scheduled waveform updates        |
 *
 * ### 6. Visual Enhancements
 * Adjust display contrast and rendering:
 *
 * | Function                        | Description                                  |
 * |----------------------------------|----------------------------------------------|
 * | `applyGammaCorrection()`        | Adjusts gamma curve for contrast             |
 * | `applyMonoLevel()`              | Controls monochrome intensity                |
 * | `applyColorFilter()`            | Adjusts color tones (for color e-ink only)   |
 * | `setWebViewContrastOptimize()`  | Enhances contrast in WebViews                |
 *
 * ### Common Usage Patterns:
 *
 * // For animations or video playback:
 * EpdController.setDisplayScheme(SCHEME_APPLICATION_ANIMATION)
 * EpdController.setViewDefaultUpdateMode(view, ANIMATION)
 *
 * // For standard reading mode:
 * EpdController.setDisplayScheme(SCHEME_NORMAL)
 * EpdController.applyGCOnce() // To remove ghosting
 *
 * // For handwriting or drawing apps:
 * EpdController.setDisplayScheme(SCHEME_SCRIBBLE)
 * EpdController.handwritingRepaint(inkView, dirtyRect)
 *
 * // To reset view to default behavior:
 * EpdController.resetViewUpdateMode(view)
 * EpdController.setDisplayScheme(SCHEME_NORMAL)
 */


/**
 * Toggles animation-optimized mode for smoother UI interactions.
 *
 * @param isAnimationMode true to enable fast/animation mode, false for normal refresh
 */
fun setAnimationMode(isAnimationMode: Boolean) {
// reference:
// https://github.com/onyx-intl/OnyxAndroidDemo/blob/d3a1ffd3af231fe4de60a2a0da692c17cb35ce31/app/OnyxPenDemo/src/main/java/com/onyx/android/eink/pen/demo/ui/PenDemoActivity.java#L500
    if (isAnimationMode) {
        OnyxSdkCompat.runEpd(Unit, "applyTransientUpdate") {
            EpdController.applyTransientUpdate(UpdateMode.ANIMATION_X)
        }
        Log.d(TAG, "Animation mode enabled")
    } else {
        OnyxSdkCompat.runEpd(Unit, "clearTransientUpdate") {
            EpdController.clearTransientUpdate(true)
        }
        Log.d(TAG, "Animation mode disabled")
    }
}

fun setRecommendedMode() {
    OnyxSdkCompat.runEpd(Unit, "setAppScopeRefreshMode") {
        EpdController.setAppScopeRefreshMode(UpdateOption.NORMAL)
    }
    Log.d(TAG, "Changed to NORMAL mode")
}

fun isRecommendedRefreshMode(): Boolean {
    val updateOption = OnyxSdkCompat.getAppScopeRefreshModeOrNull() ?: return false
    return updateOption == UpdateOption.NORMAL || updateOption == UpdateOption.REGAL
}

fun getCurRefreshModeString(): String {
    return OnyxSdkCompat.getAppScopeRefreshModeOrNull()?.toString() ?: "UNKNOWN"
}

suspend fun waitForEpdRefresh(updateOption: UpdateOption? = null) {
    val effectiveUpdateOption = updateOption ?: OnyxSdkCompat.getAppScopeRefreshModeOrNull() ?: UpdateOption.NORMAL
    Log.d(TAG, "Waiting for screen, Update mode: $updateOption")
//        Device.currentDevice().waitForUpdateFinished()
    // depending on device, it may take different amount of time to
    // refresh the screen. So for example, when closing menus, we
    // need to wait before we freeze screen.

    // Onyx library might change
    @Suppress("REDUNDANT_ELSE_IN_WHEN")
    when (effectiveUpdateOption) {
        UpdateOption.NORMAL -> {
            // HD mode
            delay(190) // On my device ~160 is the minimal delay
        }

        UpdateOption.REGAL -> {
            // regal mode
            delay(180) // On my device ~150 is the minimal delay
        }

        UpdateOption.FAST -> {
            //ultra fast, fast, balanced
            delay(20) // 5ms is problematic sometimes on balanced mode.
        }

        UpdateOption.FAST_X -> {
            // no idea what it is
            delay(4) // Minimal delay
        }

        UpdateOption.FAST_QUALITY -> {
            // no idea what it is
            delay(15)
        }

        else -> {
            // Default fallback
            Log.e(TAG, "Unknown refresh mode: $effectiveUpdateOption")
            delay(10)
        }
    }
}

/**
 * Attempts to set the refresh mode for a view using the Onyx EPDController.
 * Catches and logs exceptions to prevent crashes on unsupported devices or update modes.
 * Returns true if successful, false otherwise.
 * This is necessary because the Onyx library is unstable and unreliable.
 */
private fun tryToSetRefreshMode(view: View, mode: UpdateMode): Boolean {
    return OnyxSdkCompat.runEpd(false, "setViewDefaultUpdateMode($mode)") {
        try {
            EpdController.setViewDefaultUpdateMode(view, mode)
            Log.d(TAG, "Set update mode $mode")
            true
        } catch (e: NullPointerException) {
            Log.d(TAG, "Device does not support update mode $mode (NullPointerException): ${e.message}")
            false
        } catch (e: IllegalArgumentException) {
            Log.d(TAG, "Device does not support update mode $mode (IllegalArgumentException): ${e.message}")
            false
        } catch (e: Exception) {
            Log.e(TAG, "Unexpected error when setting update mode $mode: ${e.message}", e)
            false
        }
    }
}

fun onSurfaceInit(view: View) {
    Log.v(TAG, "onSurfaceInit, (${view.left}, ${view.top} - ${view.right}, ${view.bottom})")
    if(!tryToSetRefreshMode(view, UpdateMode.HAND_WRITING_REPAINT_MODE))
        tryToSetRefreshMode(view, UpdateMode.REGAL)
    OnyxSdkCompat.runEpd(Unit, "enablePost(global)") {
        EpdController.enablePost(1)
    }
}

fun onSurfaceChanged(view: View) {
    OnyxSdkCompat.runEpd(Unit, "enablePost(view)") {
        EpdController.enablePost(view, 1)
    }

}


fun onSurfaceDestroy(view: View, touchHelper: TouchHelper?) {
    if(touchHelper == null) return
    Log.v(TAG, "onSurfaceDestroy, (${view.left}, ${view.top} - ${view.right}, ${view.bottom})")
    touchHelper.setRawDrawingEnabled(false)
}


fun setupSurface(view: View, touchHelper: TouchHelper?, toolbarHeight: Int) {
    if(touchHelper == null) return
    // Takes at least 50ms on Note 4c,
    // and I don't think that we need it immediately
    Log.i(TAG, "Setup editable surface")
    touchHelper.debugLog(false)
    touchHelper.setRawDrawingEnabled(false)
    touchHelper.closeRawDrawing()

    // Store view dimensions locally before using in Rect
    val viewWidth = view.width
    val viewHeight = view.height

    // Guard: if the view has not been laid out yet, dimensions will be 0.
    // Calling openRawDrawing() with a zero-area limitRect causes a silent
    // "Empty region detected" failure in RawInputReader — the TouchHelper
    // is left permanently broken. Return early; updateActiveSurface() will
    // be called again from surfaceChanged() once real dimensions are known.
    if (viewWidth <= 0 || viewHeight <= 0) {
        Log.w(TAG, "setupSurface: view not measured yet (${viewWidth}x${viewHeight}), skipping openRawDrawing")
        return
    }

    val isTop = NotebookSettingsProvider.current.toolbarPosition == NotebookEditorSettings.Position.Top

    val limitRect =
        if (isTop) Rect(0, toolbarHeight, viewWidth, viewHeight)
        else Rect(0, 0, viewWidth, viewHeight - toolbarHeight)

    // Only call setExcludeRect when toolbar is visible (height > 0).
    // Passing a zero-height/width degenerate Rect also triggers "Empty region detected"
    // in RawInputReader, which causes openRawDrawing() to fail silently.
    // When no toolbar: setLimitRect(...).openRawDrawing() without setExcludeRect.
    Log.i(TAG, "setupSurface: limitRect=$limitRect toolbarHeight=$toolbarHeight viewWidth=$viewWidth viewHeight=$viewHeight")
    if (toolbarHeight > 0) {
        val excludeRect =
            if (isTop) Rect(0, 0, viewWidth, toolbarHeight)
            else Rect(0, viewHeight - toolbarHeight, viewWidth, viewHeight)
        Log.i(TAG, "setupSurface: excludeRect=$excludeRect")
        touchHelper.setLimitRect(mutableListOf(limitRect)).setExcludeRect(listOf(excludeRect))
            .openRawDrawing()
    } else {
        touchHelper.setLimitRect(mutableListOf(limitRect)).openRawDrawing()
    }

    touchHelper.setRawDrawingEnabled(true)
    Log.i(TAG, "Setup editable surface completed")

}

fun prepareForPartialUpdate(view: View, touchHelper: TouchHelper?) {
    if(touchHelper == null) return
    OnyxSdkCompat.runEpd(Unit, "prepareForPartialUpdate") {
        EpdController.setDisplayScheme(SCHEME_SCRIBBLE)
//    EpdController.useFastScheme() // the same as above
        EpdController.enableA2ForSpecificView(view)
//    EpdController.enablePost(view, 1)
        EpdController.setEpdTurbo(100)
    }
    //exit of drawing mode
    touchHelper.isRawDrawingRenderEnabled = false
    touchHelper.isRawDrawingRenderEnabled = true
}

fun refreshScreenRegion(view: View, dirtyRect: Rect) {
    if (!view.isAttachedToWindow) {
        Log.e(TAG, "View is not attached to window")
        logCallStack("refreshScreenRegion")
    }
    OnyxSdkCompat.runEpd(Unit, "refreshScreenRegion") {
        EpdController.refreshScreenRegion(
            view,
            dirtyRect.left,
            dirtyRect.top,
            dirtyRect.width(),
            dirtyRect.height(),
            UpdateMode.ANIMATION_MONO
        )
    }
//    EpdController.handwritingRepaint(view, dirtyRect)
}

//https://github.com/onyx-intl/OnyxAndroidDemo/blob/d3a1ffd3af231fe4de60a2a0da692c17cb35ce31/doc/EPD-Screen-Update.md
fun refreshScreen() {
    // TODO: It does nothing, I have no idea why.
    OnyxSdkCompat.runEpd(Unit, "repaintEveryThing") {
        EpdController.repaintEveryThing(UpdateMode.REGAL_PLUS)
    }
//    EpdController.refreshScreen(view, UpdateMode.ANIMATION_MONO)
}



fun restoreDefaults(view: View) {
//    EpdController.resetViewUpdateMode(view)
    OnyxSdkCompat.runEpd(Unit, "setDisplayScheme(normal)") {
        EpdController.setDisplayScheme(SCHEME_NORMAL)
    }

}


fun partialRefreshRegionOnce(view: View, dirtyRect: Rect, touchHelper: TouchHelper?) {
    if(touchHelper == null) return
    refreshScreenRegion(view, dirtyRect)
    resetScreenFreeze(touchHelper)
    // we need to wait before refreshing, as onyx library has its own buffer that needs to be updated. Otherwise we will refresh to correct, then  incorrect and then correct state.
//    delay(100)
//    resetScreenFreeze(touchHelper)
}

fun resetScreenFreeze(touchHelper: TouchHelper?, view: View? = null) {
    if(touchHelper == null)
    {
        Log.e(TAG, "touchHelper is null")
        return
    }
    touchHelper.isRawDrawingRenderEnabled = false
    touchHelper.isRawDrawingRenderEnabled = true
//    setRawDrawingEnabled(false)
//    setRawDrawingEnabled(true)
}

//    Device.currentDevice().invalidate(this@DrawCanvas, UpdateMode.ANIMATION_MONO);
//    EpdController.refreshScreen(view, UpdateMode.ANIMATION_MONO)
//    EpdController.setEpdTurbo(100)
//    EpdController.clearTransientUpdate(true)
//    EpdController.repaintEveryThing()
//    EpdController.setScreenHandWritingPenState(view, EpdPenManager.PEN_PAUSE)
//    EpdController.setScreenHandWritingPenState(view, EpdPenManager.PEN_DRAWING)


/**
 * Automatically toggles e‑ink animation mode when the attached subtree scrolls.
 * Works with any Compose scrollable that supports nested scroll (Lazy* and scrollable()).
 *
 * - Turns on immediately when any scroll/drag/fling starts.
 * - Turns off after [debounceOffMillis] from the end of drag/fling.
 */
fun Modifier.autoEInkAnimationOnScroll(
    debounceOffMillis: Long = 500,
    setMode: (Boolean) -> Unit = ::setAnimationMode
): Modifier = composed {
    val scope = rememberCoroutineScope()
    var offJob: Job? by remember { mutableStateOf(null) }

    fun turnOn() {
        offJob?.cancel()
        setMode(true)
    }

    fun scheduleOff() {
        offJob?.cancel()
        offJob = scope.launch {
            delay(debounceOffMillis)
            setMode(false)
        }
    }

    val connection = remember(debounceOffMillis, setMode) {
        object : NestedScrollConnection {
            // Any pre-scroll (user drag) -> ON
            override fun onPreScroll(available: Offset, source: NestedScrollSource): Offset {
                if (available != Offset.Zero) turnOn()
                return Offset.Zero
            }

            // Any post-scroll (child consumed) -> ON
            override fun onPostScroll(
                consumed: Offset,
                available: Offset,
                source: NestedScrollSource
            ): Offset {
                if (consumed != Offset.Zero) {
                    turnOn()
                } else if (source == NestedScrollSource.UserInput && available == Offset.Zero) {
                    // Likely drag end without fling -> schedule OFF
                    scheduleOff()
                }
                return Offset.Zero
            }

            // Fling start -> ON
            override suspend fun onPreFling(available: Velocity): Velocity {
                turnOn()
                return Velocity.Zero
            }

            // Fling finished -> schedule OFF
            override suspend fun onPostFling(consumed: Velocity, available: Velocity): Velocity {
                scheduleOff()
                return Velocity.Zero
            }
        }
    }

    DisposableEffect(Unit) {
        onDispose { offJob?.cancel() }
    }

    this.nestedScroll(connection)
}

object DeviceCompat {
    /**
     * True when running on an ONYX BOOX device and Onyx SDK classes are present.
     * Checks manufacturer/brand and that a core Onyx class exists at runtime.
     */
    val isOnyxDevice: Boolean by lazy {
        isOnyxManufacturer() && isOnyxSdkAvailable()
    }

    private fun isOnyxManufacturer(): Boolean {
        return "ONYX".equals(Build.MANUFACTURER, ignoreCase = true)
                || "ONYX".equals(Build.BRAND, ignoreCase = true)
    }

    private fun isOnyxSdkAvailable(): Boolean {
        return try {
            Class.forName("com.onyx.android.sdk.pen.TouchHelper")
            true
        } catch (e: ClassNotFoundException) {
            false
        }
    }
}
